{% set version = "0.7.1" %}
# Latest python_min is defined in https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml

package:
  name: class-resolver
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/class-resolver/class_resolver-{{ version }}.tar.gz
  sha256: 86f73b8cc5ed9111b7d9c5e331b51856a32f205179c66a56a9c520d0f6e82f66

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build >=0.6.6,<1.0
  run:
    - python >={{ python_min }}
    - typing_extensions

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - class_resolver
  commands:
    - pip check

about:
  home: https://github.com/cthoyt/class-resolver
  summary: Lookup and instantiate classes with style.
  license: MIT
  license_file: LICENSE
  doc_url: https://class-resolver.readthedocs.io
  dev_url: https://github.com/cthoyt/class-resolver

extra:
  recipe-maintainers:
    - jamesmyatt
