{% set version = "0.6.0" %}
# Latest python_min is defined in https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml

package:
  name: class-resolver
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/class-resolver/class_resolver-{{ version }}.tar.gz
  sha256: 8a3c20ab771925477f65cad8a49bb431e11543c82fbfadbf611c6769228a6cae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build
  run:
    - python >={{ python_min }}
    - importlib-metadata >3.6  # strictly, py<310
    - typing_extensions

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - class_resolver
  commands:
    - pip check

about:
  home: https://github.com/cthoyt/class-resolver
  summary: Lookup and instantiate classes with style.
  license: MIT
  license_file: LICENSE
  doc_url: https://class-resolver.readthedocs.io
  dev_url: https://github.com/cthoyt/class-resolver

extra:
  recipe-maintainers:
    - jamesmyatt
